### ISSUE TITLE
Docs build times out after 6 hours

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#119]
Between 6 and 23 days ago, the docs build began hannging until the workflow is terminated at 6 hours. It looks like this happens when it encounters the `Turing.pointwise_loglikelihoods` command in the Quickstart https://github.com/arviz-devs/ArviZ.jl/blame/v0.5.0/docs/src/quickstart.md#L177. When I run the Turing example locally and reach that line, my terminal fills up with many copies of the following warning:
```julia
┌ Warning: the following keys were not found in `vi`, and thus `kernel!` was not applied to these: ["acceptance_rate", "hamiltonian_energy", "hamiltonian_energy_error", "is_accept", "log_density", "lp", "max_hamiltonian_energy_error", "n_steps", "nom_step_size", "numerical_error", "step_size", "tree_depth"]
```
This message was added in https://github.com/TuringLang/DynamicPPL.jl/pull/216, which was released in DynamicPPL v0.10.9 19 days ago, so it seems likely that these warnings are causing the hang (sometimes Documenter can't handle many warnings or print statements). Pinning DynamicPPL to v0.10.8 causes the docs build to succeed.

@torfjelde is there something that we need to change about the Quickstart example to avoid all of these warnings? Or is this a DynamicPPL bug?

**Comment by torfjelde** [comment]
Ah, crap. Really sorry about this!

But yes, this can be easily be fixed; I'll make a PR:)
