### ISSUE TITLE
Don't run CmdStan in test

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#13]
Running CmdStan in the test requires us to download and compile cmdstan, which roughly doubles the runtime of the test suite. Perhaps we can check in the cmdstan output files and read them in using CmdStan's functions to get the `Chains`.

**Comment by ahartikainen** [comment]
You can cache cmdstan and compiled models

See travis file in https://github.com/stan-dev/cmdstanpy

**Comment by sethaxen** [comment]
Oh that's convenient. Thanks for the heads up!
