### ISSUE TITLE
Removing MonteCarloMeasurements support

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#192]
We added have conversions from `MonteCarloMeasurements.Particles` to `InferenceData` in the early days of the package to support Soss, which used `Particles` as its storage type. This is no longer the case though, and I'm not aware of any PPLs using `Particles`. If this functionality is unused, I'd prefer to remove it so we don't need to maintain it.

@cscherrer @baggepinnen do either of you use this functionality or know of someone who does?

**Comment by baggepinnen** [comment]
I'm not using ArviZ either so I think it's fine to remove the support. 

The 
> Julia needs to know whether particles should be treated as a scalar (and so broadcasting over its elements) or as an array

problem has been "solved" by no longer trying to be "smart" and do what the user *might* want, and instead adopt the filosophy that `Particles` are always scalars, and any function that operates on the individual samples have been given a new name. Having said that, I understand why `Particles` are a suboptimal fit for Soss, but it was fun exploring the limits of the approach :)
