### ISSUE TITLE
Separating InferenceData and Dataset into their own package

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#207]
Should we move `InferenceData` and `Dataset` into their own lightweight package? On my machine such a package, which would only depend on DimensionalData, Dates, and OrderedCollections, has a load time of ~5.5ms (compare with ArviZ's current ~1.5s).

This has some benefits:
- It makes it easier for PPLs to implement their own `convert_to_inference_data` method instead of us needing to maintain it.
- It allows for other packages to implement methods that expect `InferenceData` inputs without depending on all of ArviZ.
- It opens up the possibility for `InferenceData` to be an official storage format for a PPL, similar to how PyMC stores results in `InferenceData`.

The main downsides are:
- slightly harder to maintain. Instead of making changes in one repo (ArviZ), major changes to `InferenceData` would require changes to 2 packages
- `InferenceData` being decoupled from ArviZ means `arviz_version` should not be part of the `InferenceData` schema. This runs counter to one suggestion in https://github.com/arviz-devs/arviz/issues/2064#issue-1292375546
- naming is annoying. Ideally the package would be InferenceData.jl, but that will conflict with the name `InferenceData`, so something like InferenceDataObject.jl would likely be the name.

I think the upsides outweigh the downsides, so my main question is how likely is it that such a package would actually be used by others downstream.

@ParadaCarleton you had expressed interest in such a package. What do you think?

**Comment by ParadaCarleton** [comment]
Sounds great to me! Only complaint is that InferenceDataObject.jl is a mouthful; how about InferenceObjects.jl?

**Comment by sethaxen** [comment]
> Only complaint is that InferenceDataObject.jl is a mouthful; how about InferenceObjects.jl?

Maybe!

How likely do you think you or others are to use this as its own package?

**Comment by sethaxen** [comment]
One more note. For this to be truly standalone, we would need NetCDF I/O in this package (see #208). That could be put off temporarily.

I haven't compared usage, but NetCDF.jl takes ~4ms to load on my machine, while NCDatasets.jl takes ~115ms, so we'd certainly prefer to use the former if it has the necessary features.

**Comment by OriolAbril** [comment]
Not sure if it is of much (or any) help, but either netcdf or zarr can be used for I/O with "InferenceData compliant" structures. In my opinion, both would be optional dependencies, with neither being required.

The python version of ArviZ has a hard dependency on netcdf, optional one on zarr. We should move towards both being optional, and part of the CZI work will go on that direction. The example data relies on netcdf, but other than that, netcdf only affects the from/to_netcdf methods.

In julia the official zarr I/O library seems to be https://github.com/JuliaIO/Zarr.jl

**Comment by sethaxen** [comment]
> Not sure if it is of much (or any) help, but either netcdf or zarr can be used for I/O with "InferenceData compliant" structures. In my opinion, both would be optional dependencies, with neither being required.

Ah, good to know, thanks. Since there's more than one way one might serialize a Python or Julia object to one of these formats, should a description of that also be part of the InferenceData spec? At the moment I'm writing test netCDF and Zarr files out using Python ArviZ to see what the outputs look like so I can reproduce them in Julia.

**Comment by OriolAbril** [comment]
I am not sure I follow this. Do you have an example? As far as I know, xarray objects that contain data or coordinates of `object` dtype for example can't be saved to disk, you'd need to convert them to the types recognized and accepted by the netcdf/zarr i/o libraries doesn't this mean the i/o libraries define these fileformat types <-> native python/julia types mappings?

**Comment by sethaxen** [comment]
The only concrete example I have is how dimensions are serialized. Python ArviZ serializes these the same way as variables, and then it adds a specific attribute to all variables in a group specifying their dimensions. The single dimension of a dimension is itself. I'm not familiar enough with Zarr or netCDF; maybe this is already in their spec? Otherwise, it might be a good idea to document this.

**Comment by OriolAbril** [comment]
Thanks, I'll try to see where/to whom this should be asked and ask it. I agree that if this is not part of the zarr/netcdf spec we should document it, but I'd rather not go down this hole if possible

**Comment by ParadaCarleton** [comment]
> > Only complaint is that InferenceDataObject.jl is a mouthful; how about InferenceObjects.jl?
> 
> Maybe!
> 
> How likely do you think you or others are to use this as its own package?

I'd definitely use it--I've been writing a lot of code for Bayesian plotting in Makie+AlgebraOfGraphics, and I'll probably spin it off into a package at some point.

For this particular use case, we could instead split off an `ArvizBase` that includes everything but the graphs.

**Comment by sethaxen** [comment]
Nice! I'll prioritize this splitting then.

 ArviZ's diagnostics are moving to MCMCDiagnosticTools, and its statistics will be their own package. Integration with plotting packages will be in their own packages. E.g. ArviZMakie would implement ArviZ's plots using Makie. What I'm undecided on is whether ArviZMakie would depend on ArviZ (so a user would usually load ArviZMakie or ArviZPlots instead of ArviZ) or the other way around (using Requires). The SciML org has been moving away from the latter model and towards the former model. In this case, ArviZ itself would be like the ArviZBase you're describing.

For ArviZMakie I'm planning on using AoG internally as well, and I'd welcome a collaboration if you're interested.

**Comment by sethaxen** [comment]
@ParadaCarleton `InferenceData` and `Dataset` have been split out into their own package [InferenceObjects.jl](https://github.com/arviz-devs/InferenceObjects.jl), and the registration PR is open. The load time for the package is ~100ms on my laptop on Julia v1.8.

**Comment by ParadaCarleton** [comment]
> @ParadaCarleton `InferenceData` and `Dataset` have been split out into their own package [InferenceObjects.jl](https://github.com/arviz-devs/InferenceObjects.jl), and the registration PR is open. The load time for the package is ~100ms on my laptop on Julia v1.8.

Nice, thank you so much!
