### ISSUE TITLE
Installing ArviZ.jl in a new environment results in arviz version error (0.13.0 or greater but found version 0.12.1)

### ISSUE THREAD

**Issue by SebastianCallh** [arviz-devs/ArviZ.jl#246]
Hello!
I tried to install ArviZ v0.7.0 in a new Julia project and Python virtualenv on Julia 1.8.2 without having (python) arviz istalled. This resulted in
`Warning: ArviZ.jl only officially supports arviz version 0.13.0 or greater but found version 0.12.1.`.

I was confused by it finding version 0.12.1 when I do not have any version installed, but I went ahead and pip installed arviz 0.14.0 in the python environment I was launching Julia from which should resolve the issue. To my surprise it didn't!
Where is ArviZ.jl looking for the python arviz installation? Could the error message be misleading? Have I completely misunderstood the setup?

**Comment by sethaxen** [comment]
ArviZ.jl is configured to use the Python executable and environment PyCall is currently built to use. To use PyCall with a virtual environment, you may need to take special steps: https://github.com/JuliaPy/PyCall.jl#python-virtual-environments.

You must already have had a version of Python ArviZ installed in the environment or ArviZ.jl wouldn't have been able to find v0.12.1. When PyCall is configured to use the Julia conda environment, ArviZ.jl could automatically upgrade python dependencies for you, but in other environments you'll need to do the upgrading yourself.

**Comment by SebastianCallh** [comment]
Thank you for explaining. It looks like I am in the land of wacky Python environments. I gave up and installed ArviZ.jl
with `PYTHON="" julia -e 'using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("ArviZ")'` as specified in the documentation and it worked.  Thank you for your work on this package! I am very happy I can do my Bayesian stuff in Julia :+1:

**Comment by sethaxen** [comment]
Great! Glad to hear it works! We're piece by piece implementing features in pure Julia, some of them in more lightweight component packages, so hopefully in the next few months we can avoid these Python environment issues entirely.

> Thank you for your work on this package! I am very happy I can do my Bayesian stuff in Julia +1

You're welcome!
