### ISSUE TITLE
Support ArviZ's Bokeh backend

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#30]
ArviZ plots are [gradually getting a Bokeh backend](https://github.com/arviz-devs/arviz/projects/1#card-29021071) in addition to the existing matplotlib backend. It would be nice if we could support this here. Specifically, we would like Bokeh plots to appear in interactive contexts instead of just the HTML file they currently are saved in.

[Bokeh.jl](https://github.com/samuelcolvin/Bokeh.jl) is pre-1.0 and discontinued, so we would need to find our own ideally minimal solution.

**Comment by ahartikainen** [comment]
There might be a way to return a javascript/html code for the bokeh plot and then maybe that could be wrapped to some window?

**Comment by sethaxen** [comment]
If that's the case, it might be as easy as wrapping whatever that object is in a custom Julia type and then implementing a `show` like we do for `Dataset`. A good place to start looking is to see how bokeh's IPython support works.

**Comment by sethaxen** [comment]
I don't know though if the same approach would work in IDEs like Juno or VS Code though.

**Comment by ahartikainen** [comment]
Maybe you could wrap part of this: https://github.com/samuelcolvin/Bokeh.jl/blob/master/src/display.jl

**Comment by sethaxen** [comment]
Yeah, I need to figure out how that works. Just to document a few observations:

This example works but loads HTML plot in a new window:

```julia
using ArviZ
idata = load_arviz_data("centered_eight")
plot_trace(idata; backend="bokeh")
```

If we set `output_notebook` we get nothing:

```julia
backends = ArviZ.arviz.backends
backends.output_notebook()
```

It's too soon to say, but it might be a problem that ArviZ calls `show` within the plotting routines, since as far as I can tell, there's not a function like `plt.gcf` in bokeh that gives us the object that was passed to `show`.

**Comment by ahartikainen** [comment]
Our Bokeh code returns a bokeh figure object (or an array of figure objects; None on locations without object --> this can be combined with `gridplot` from bokeh and them send to show)
