### ISSUE TITLE
Return dataframes from DataFrames instead of Pandas

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#34]
`Pandas.DataFrame`s are functional but nonintuitive and don't render usefully in Jupyter notebooks (e.g. not all columns are shown; should be addressed by https://github.com/JuliaPy/Pandas.jl/pull/63). More importantly, Pandas.jl doesn't appear to be actively maintained. We should instead convert to `DataFrames.DataFrame`, which will be more useful in Julia and render correctly in HTML.

The only two challenges here are 1) converting the index to a column and 2) some columns have numpy datatypes that aren't converted to Julia types by PyCall.

**Comment by ahartikainen** [comment]
In the Python side: 

    # create a "index" column
    df.reset_index(drop=False)

    # or without resetting
    df["index"] = df.index

What columns are those?

We have some columns that should be `int` but might contain float, because nan is float.
Or do you mean the difference between `np.int32` and `int`?

**Comment by sethaxen** [comment]
> Or do you mean the difference between np.int32 and int? 

Yes that's right. For some reason  PyCall didn't convert that to a Julia type. I can post an example later.

**Comment by sethaxen** [comment]
`arviz.compare` returns a dataframe with a `warning` column whose value is of type `numpy.bool_`. `arviz.loo` and `arviz.waic` produced dataframes have an entry `n_data_points` whose type is `numpy.int64`. These are not converted, while all other int and bool types are, which indicates something is different about them.

The weird thing is that if I call `arviz.r2_score` on random inputs and then try again calling the above methods, conversion works just fine. I'm not certain whether that's a PyCall issue or an ArviZ issue.

**Comment by ahartikainen** [comment]
That sounds... interesting. Is there a way to manually change input dtypes or should it just work.

I think there are some typos in PyCall code (probably), which ignore numpy dtypes (they are essentially the same as C dtypes (?))

**Comment by ahartikainen** [comment]
Maybe its related to this https://github.com/JuliaPy/PyCall.jl/issues/386

**Comment by sethaxen** [comment]
> That sounds... interesting. Is there a way to manually change input dtypes or should it just work.

It should just work. And it does for all of the other columns.

> Maybe its related to this [JuliaPy/PyCall.jl#386](https://github.com/JuliaPy/PyCall.jl/issues/386)

Thanks for hunting that down. I'll look into it later (it's later here).

Here's an example of the failure using #35:

```julia
julia> using ArviZ

julia> idata = load_arviz_data("centered_eight");

julia> compare(Dict("a"=>idata, "b"=>idata))
2×10 DataFrames.DataFrame
│ Row │ name   │ rank  │ waic    │ p_waic   │ d_waic  │ weight  │ se      │ dse     │ warning        │ waic_scale │
│     │ String │ Int64 │ Float64 │ Float64  │ Float64 │ Float64 │ Float64 │ Float64 │ PyCall…        │ String     │
├─────┼────────┼───────┼─────────┼──────────┼─────────┼─────────┼─────────┼─────────┼────────────────┼────────────┤
│ 1   │ b      │ 0     │ 61.516  │ 0.901656 │ 0.0     │ 0.5     │ 2.56805 │ 0.0     │ PyObject False │ deviance   │
│ 2   │ a      │ 1     │ 61.516  │ 0.901656 │ 0.0     │ 0.5     │ 2.56805 │ 0.0     │ PyObject False │ deviance   │

julia> loo(idata)
1×7 DataFrames.DataFrame
│ Row │ loo     │ loo_se  │ p_loo    │ n_samples │ n_data_points │ warning │ loo_scale │
│     │ Float64 │ Float64 │ Float64  │ Int64     │ PyCall…       │ Bool    │ String    │
├─────┼─────────┼─────────┼──────────┼───────────┼───────────────┼─────────┼───────────┤
│ 1   │ 61.6207 │ 2.85367 │ 0.954053 │ 2000      │ PyObject 8    │ 0       │ deviance  │

julia> waic(idata)
1×7 DataFrames.DataFrame
│ Row │ waic    │ waic_se │ p_waic   │ n_samples │ n_data_points │ warning │ waic_scale │
│     │ Float64 │ Float64 │ Float64  │ Int64     │ PyCall…       │ Bool    │ String     │
├─────┼─────────┼─────────┼──────────┼───────────┼───────────────┼─────────┼────────────┤
│ 1   │ 61.516  │ 2.83107 │ 0.901656 │ 2000      │ PyObject 8    │ 0       │ deviance   │

julia> r2_score(randn(10), randn(10))
1×2 DataFrames.DataFrame
│ Row │ r2       │ r2_std  │
│     │ Float64  │ Float64 │
├─────┼──────────┼─────────┤
│ 1   │ 0.273987 │ 0.0     │

julia> compare(Dict("a"=>idata, "b"=>idata))
2×10 DataFrames.DataFrame
│ Row │ name   │ rank  │ waic    │ p_waic   │ d_waic  │ weight  │ se      │ dse     │ warning │ waic_scale │
│     │ String │ Int64 │ Float64 │ Float64  │ Float64 │ Float64 │ Float64 │ Float64 │ Bool    │ String     │
├─────┼────────┼───────┼─────────┼──────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────────┤
│ 1   │ b      │ 0     │ 61.516  │ 0.901656 │ 0.0     │ 0.5     │ 2.6417  │ 0.0     │ 0       │ deviance   │
│ 2   │ a      │ 1     │ 61.516  │ 0.901656 │ 0.0     │ 0.5     │ 2.6417  │ 0.0     │ 0       │ deviance   │

julia> loo(idata)
1×7 DataFrames.DataFrame
│ Row │ loo     │ loo_se  │ p_loo    │ n_samples │ n_data_points │ warning │ loo_scale │
│     │ Float64 │ Float64 │ Float64  │ Int64     │ Int64         │ Bool    │ String    │
├─────┼─────────┼─────────┼──────────┼───────────┼───────────────┼─────────┼───────────┤
│ 1   │ 61.6207 │ 2.85367 │ 0.954053 │ 2000      │ 8             │ 0       │ deviance  │

julia> waic(idata)
1×7 DataFrames.DataFrame
│ Row │ waic    │ waic_se │ p_waic   │ n_samples │ n_data_points │ warning │ waic_scale │
│     │ Float64 │ Float64 │ Float64  │ Int64     │ Int64         │ Bool    │ String     │
├─────┼─────────┼─────────┼──────────┼───────────┼───────────────┼─────────┼────────────┤
│ 1   │ 61.516  │ 2.83107 │ 0.901656 │ 2000      │ 8             │ 0       │ deviance   │
```

**Comment by sethaxen** [comment]
But look at [that documentation](https://arviz-devs.github.io/ArviZ.jl/previews/PR35/quickstart/#Convert-to-InferenceData-1)!

**Comment by ahartikainen** [comment]
Looks great. Did DataFrames fix it?

**Comment by sethaxen** [comment]
Yup. It just behaves better in Julia than the Pandas wrapper. Gets rendered to HTML when necessary too.

**Comment by sethaxen** [comment]
@ahartikainen after some trouble-shooting, I'm fairly certain the issue related to https://github.com/JuliaPy/PyCall.jl/issues/744. I'm reaching out to see if anyone in the Julia community can shed some light on the issue.

**Comment by sethaxen** [comment]
It was indeed the above PyCall issue! Turns out PyCall waits to load NumPy types until it thinks NumPy is needed, which is when a user first sends a julia array to Python, not the other way around. This explains why conversions failed early on but worked later. Probably an array got sent in there somewhere:

```julia
julia> using ArviZ

julia> idata = load_arviz_data("centered_eight");

julia> compare(Dict("a"=>idata, "b"=>idata))
2×10 DataFrames.DataFrame
│ Row │ name   │ rank  │ loo      │ p_loo    │ d_loo   │ weight  │ se      │ dse     │ warning        │ loo_scale │
│     │ String │ Int64 │ Float64  │ Float64  │ Float64 │ Float64 │ Float64 │ Float64 │ PyCall…        │ String    │
├─────┼────────┼───────┼──────────┼──────────┼─────────┼─────────┼─────────┼─────────┼────────────────┼───────────┤
│ 1   │ b      │ 0     │ -30.8104 │ 0.954053 │ 0.0     │ 0.5     │ 1.3373  │ 0.0     │ PyObject False │ log       │
│ 2   │ a      │ 1     │ -30.8104 │ 0.954053 │ 0.0     │ 0.5     │ 1.3373  │ 0.0     │ PyObject False │ log       │

julia> using PyCall

julia> PyCall.npy_integer
PyObject NULL

julia> PyObject([1.0])
PyObject array([1.])

julia> PyCall.npy_integer
PyObject <class 'numpy.integer'>

julia> compare(Dict("a"=>idata, "b"=>idata))
2×10 DataFrames.DataFrame
│ Row │ name   │ rank  │ loo      │ p_loo    │ d_loo   │ weight  │ se      │ dse     │ warning │ loo_scale │
│     │ String │ Int64 │ Float64  │ Float64  │ Float64 │ Float64 │ Float64 │ Float64 │ Bool    │ String    │
├─────┼────────┼───────┼──────────┼──────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┤
│ 1   │ b      │ 0     │ -30.8104 │ 0.954053 │ 0.0     │ 0.5     │ 1.33699 │ 0.0     │ 0       │ log       │
│ 2   │ a      │ 1     │ -30.8104 │ 0.954053 │ 0.0     │ 0.5     │ 1.33699 │ 0.0     │ 0       │ log       │
```

Simply sending a dummy array at import should fix this.
