### ISSUE TITLE
Changes for new org

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/ArviZ.jl#9]
ArviZ.jl is now hosted under the arviz-devs organization. 🎉 

GitHub already forwarded the URL, but a few housekeeping items need to be handled:

- [x] Update all references to "sethaxen" to "arviz-devs"
- [x] Make sure Travis CI is working
- [x] Ensure documentation is being deployed to the right place (probably https://arviz-devs.github.io/ArviZ.jl)
- [x] Remove old analytics code
- [x] Submit a PR to Julia's general package registry to point the URL to the right place (once v0.1.0 has been released, see https://github.com/JuliaRegistries/General/pull/5280)
- [x] Adapt `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` from https://github.com/arviz-devs/arviz for this repo
- [x] Link to this repo from the readme at https://github.com/arviz-devs/arviz

If I'm missing anything, feel free to comment.

**Comment by OriolAbril** [comment]
Linked to this repo in ArviZ readme and docs in https://github.com/arviz-devs/arviz/pull/894
